# fruits = []
# f1 = input("Enter Fruit Name: ")
# fruits.append(f1)
# f2 = input("Enter Fruit Name: ")
# fruits.append(f2)
# f3 = input("Enter Fruit Name: ")
# fruits.append(f3)
# f4 = input("Enter Fruit Name: ")
# fruits.append(f4)
# f5 = input("Enter Fruit Name: ")
# fruits.append(f5)
# f6 = input("Enter Fruit Name: ")
# fruits.append(f6)
# f7 = input("Enter Fruit Name: ")
# fruits.append(f7)
# print(fruits)

marks = []
f1 = int(input("Enter Marks Please: "))
marks.append(f1)
f2 = int(input("Enter Marks Please: "))
marks.append(f2)
f3 = int(input("Enter Marks Please: "))
marks.append(f3)
f4 = int(input("Enter Marks Please: "))
marks.append(f4)
f5 = int(input("Enter Marks Please: "))
marks.append(f5)
f6 = int(input("Enter Marks Please: "))
marks.append(f6)
f7 = int(input("Enter Marks Please: "))
marks.append(f7)
print(marks)
marks.sort()
print(marks)
